function C = func_CombinedCourse(R,turnX)
%FUNC_COMBINEDCOURSE Shared geometry and friction split for DLC + J-turn.
if nargin < 1 || isempty(R), R = 70; end
if nargin < 2 || isempty(turnX), turnX = 280; end
C = struct('dlc_end_x',200, 'mu_switch_x',230, ...
    'turn_x',turnX, 'turn_radius',R, 'exit_length',100, ...
    'mu_dlc',0.5, 'mu_jturn',0.85, 'target_kmh',90, ...
    'turn_target_kmh',80, 'speed_ramp_m',10);
end
